name: orders_tests

on:
  pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install and Test
        run: cd orders && npm i && npm run test:ci
